#!/bin/bash
# Run tests for distributedSMOS
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 0 0 20 20 50 50 1000 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 0 1 20 20 50 50 1000 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 0 2 20 20 50 50 1000 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 0 3 20 20 50 50 1000 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 0 4 20 20 50 50 1000 10

# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 1 0 0 20 20 50 50 500 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 1 0 1 20 20 50 50 500 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 1 0 2 20 20 50 50 500 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 1 0 3 20 20 50 50 500 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 1 0 4 20 20 50 50 500 10



# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 0 1 20 20 50 50 1000 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 1 1 20 20 50 50 1000 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 3 1 20 20 50 50 1000 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 9 1 20 20 50 50 1000 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 1 0 1 20 20 50 50 500 10
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 1 1 1 20 20 50 50 500 10

mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 0 1 15 20 100 100 101 10
mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 2 0 1 15 20 100 100 101 10
mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 1 0 1 15 20 100 100 101 10
mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 1 1 15 20 100 100 101 10
mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 1 1 1 15 20 100 100 101 10
mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 3 1 15 20 100 100 101 10
mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 9 1 15 20 100 100 101 10
