#!/bin/bash
# Run tests for distributedSMOS
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 0 0 22 22 50 50 800 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 0 1 22 22 50 50 800 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 0 2 22 22 50 50 800 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 0 3 22 22 50 50 800 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 0 4 22 22 50 50 800 10

# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 1 0 0 22 22 50 50 500 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 1 0 1 22 22 50 50 500 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 1 0 2 22 22 50 50 500 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 1 0 3 22 22 50 50 500 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 1 0 4 22 22 50 50 500 10



# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 0 1 22 22 50 50 800 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 1 1 22 22 50 50 800 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 3 1 22 22 50 50 800 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 9 1 22 22 50 50 800 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 1 0 1 22 22 50 50 500 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 1 1 1 22 22 50 50 500 10



# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 0 1 15 25 100 100 101 10
# mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 2 0 1 15 25 100 100 101 10
mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 1 0 1 15 25 100 100 101 10
mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 1 1 15 25 100 100 101 10
mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 1 1 1 15 25 100 100 101 10
mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 3 1 15 25 100 100 101 10
mpirun -np 4 -H zermelo,peano,kleene,rosser ./runTestsDistributedSMOS 0 9 1 15 25 100 100 101 10

# exit
# ssh bollee
# cd GGMS-Distributed/DistributedSMOS
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 0 0 20 20 50 50 1000 1
# exit
# ssh bollee
# cd GGMS-Distributed/DistributedSMOS
# mpirun -np 4 -hosts bollee,bellman,mccarthy,householder ./runTestsDistributedSMOS 0 0 0 20 20 50 50 1000 1


